package employee;

import java.util.Random;

public class EmployeeCheck {
    public static void main(String[] args) {

        // random class is used for generate pseudo-random-numbers
        /*
        Pseudo-random values :
            numbers look random .but they are not truly random .they are generated by fixed algoritham inside computer.
        */
        Random random = new Random();
        int attendence = random.nextInt(2);
        if(attendence == 1){
            System.out.println("employee is present");
        }else{
            System.out.println("employee is not present");
        }
    }
}
